[changelog]
header = """
# RinUI Gallery
{% if tag | startswith("alpha-") %}
Alpha `{{ version }}` version
{% elif tag | startswith("beta-") %}
Beta `{{ version }}` version
{% else %}
Release `{{ version }}` version
{% endif %}

> [!TIP]
> See also [PyPi](https://pypi.org/project/rinui/)

## What's Changed
> Still **refactoring** the gallery pages
"""

body = """
{% if commits | len == 0 %}
No changes.
{% else %}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}:
{% for commit in commits %}
- {{ commit.message | trim }}
{% endfor %}
{% endfor %}
{% endif %}
"""

footer = """
**Full Changelog**: {{ range.compare_url }}
"""

trim = true

[git]
conventional_commits = true
filter_unconventional = true

tag_pattern = '^(alpha|beta|v)?-?\d+\\.\\d+\\.\\d+$'

commit_parsers = [
  { message = "^feat\\(core\\):", group = "RinUI Core" },
  { message = "^feat\\(controls\\):", group = "New Controls" },
  { message = "^update\\(controls\\):", group = "Updated Controls" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^(chore|ci|refactor|style|docs|test)", group = "Chore" },
]

unclassified_group = "Other Changes"
topo_order = false
sort_commits = "topo"
