[changelog]
header = """
# RinUI Gallery
{% if tag | startswith("alpha-") %}
Alpha `{{ version }}` version
{% elif tag | startswith("beta-") %}
Beta `{{ version }}` version
{% else %}
{{ "" }}
{% endif %}

> [!TIP]
> See also [PyPi](https://pypi.org/project/rinui/)

## What's Changed
"""

body = """
{% if commits | len == 0 %}
No changes.
{% else %}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}:
{% for commit in commits %}
- {{ commit.message | trim }}
{% endfor %}
{% endfor %}
{% endif %}
"""

footer = """
**Full Changelog**: {{ range.compare_url }}
"""

trim = true

[git]
conventional_commits = true
filter_unconventional = true
tag_pattern = '^(alpha|beta|v)?-?\d+\.\d+\.\d+$'

commit_parsers = [
  { message = "^feat", group = "New Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^(chore|ci|refactor|style|docs|test)", group = "Chore" },
]

# fallback
unclassified_group = "Other Changes"
